name: Validación de ficheros de contenidos

on:
  pull_request:
  workflow_dispatch:

env:
  DATA_DIR: data
  META_DIR: meta-data
jobs:

  validar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install js-yaml ajv
      - name: validar contra esquema
        run: node .github/validar-schema.js
